name: Deploy React Vite (DEV)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy & restart PM2
        run: |
          cd /home/ubuntu/trello-frontend
          git pull origin dev
          npm install
          npm run build
          pm2 restart trello-frontend
