name: Deploy React Vite (DEV)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy FE via SSH
        run: |
          ssh fe_vm << 'EOF'
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            node -v
            pnpm -v

            cd /home/ubuntu/trello-frontend

            echo "Sync code"
            git fetch origin
            git checkout dev
            git reset --hard origin/dev

            echo "Install deps"
            pnpm install --frozen-lockfile

            echo "Build"
            pnpm build

            echo "Restart FE"
            pm2 restart trello-fe --update-env
            pm2 save
          EOF
